"""user transaction limits

Revision ID: 9987d7528550
Revises: e320af4416a9
Create Date: 2026-09-15 11:25:51.356214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9987d7528550'
down_revision: Union[str, None] = 'e320af4416a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with a server_default so existing rows are backfilled, then drop the
    # default so the application-level default governs new rows.
    op.add_column(
        'users',
        sa.Column('per_txn_limit', sa.BigInteger(), nullable=False,
                  server_default='50000000'),
    )
    op.add_column(
        'users',
        sa.Column('daily_limit', sa.BigInteger(), nullable=False,
                  server_default='200000000'),
    )
    op.alter_column('users', 'per_txn_limit', server_default=None)
    op.alter_column('users', 'daily_limit', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_limit')
    op.drop_column('users', 'per_txn_limit')
    # ### end Alembic commands ###
