"""electricity bill payments and transaction pin

Revision ID: d09b0147dde3
Revises: bc03d57e1cf0
Create Date: 2026-09-15 10:11:04.959898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09b0147dde3'
down_revision: Union[str, None] = 'bc03d57e1cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_meter_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=False),
    sa.Column('meter_number', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricity_meter_validations_token'), 'electricity_meter_validations', ['token'], unique=True)
    op.create_index(op.f('ix_electricity_meter_validations_user_id'), 'electricity_meter_validations', ['user_id'], unique=False)
    op.create_table('bill_payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=False),
    sa.Column('meter_number', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_payment_transactions_transaction_id'), 'bill_payment_transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_bill_payment_transactions_user_id'), 'bill_payment_transactions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('transaction_pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transaction_pin_hash')
    op.drop_index(op.f('ix_bill_payment_transactions_user_id'), table_name='bill_payment_transactions')
    op.drop_index(op.f('ix_bill_payment_transactions_transaction_id'), table_name='bill_payment_transactions')
    op.drop_table('bill_payment_transactions')
    op.drop_index(op.f('ix_electricity_meter_validations_user_id'), table_name='electricity_meter_validations')
    op.drop_index(op.f('ix_electricity_meter_validations_token'), table_name='electricity_meter_validations')
    op.drop_table('electricity_meter_validations')
    # ### end Alembic commands ###
