"""transaction reconciliation fields

Revision ID: d4fc5408c8f7
Revises: 90416a885662
Create Date: 2026-09-15 11:52:17.383599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fc5408c8f7'
down_revision: Union[str, None] = '90416a885662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('pending_reconciliation', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transactions', sa.Column('reconcile_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('transactions', 'pending_reconciliation', server_default=None)
    op.alter_column('transactions', 'reconcile_attempts', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reconcile_attempts')
    op.drop_column('transactions', 'pending_reconciliation')
    # ### end Alembic commands ###
